#!/usr/bin/env bash

brew cask install alfred
brew cask install vlc
brew cask install sketch 
brew cask install appcleaner 
brew cask install arq 
brew cask install blockblock 
brew cask install cyberduck 
brew cask install doxie 
brew cask install gnucash 
brew cask install google-chrome 
brew cask install imageoptim 
brew cask install postman 
brew cask install transmission 
brew cask install zeplin 
brew cask install calibre 
brew cask install the-unarchiver 
brew cask install visual-studio-code 
brew cask install sublime-text
brew cask install spotify 
brew cask install fork 
brew cask install google-drive-file-stream 
brew cask install rectangle 
brew cask install istat-menus  
brew cask install whatsapp 
brew cask install adguard
brew cask install audacity
brew cask install obsidian
brew cask install bitwarden
brew cask install cloudflare-warp
brew cask install drawio
brew cask install flow
brew cask install nucleo
brew cask install obs
brew cask install omnidisksweeper
brew cask install prusaslicer
brew cask install slack
