#!/usr/bin/env bash

brew cask install alfred
brew cask install vlc
brew cask install sketch 
brew cask install appcleaner 
brew cask install applepi-baker 
brew cask install arq 
brew cask install blockblock 
brew cask install cyberduck 
brew cask install doxie 
brew cask install gnucash 
brew cask install google-chrome 
brew cask install handbrake 
brew cask install imageoptim 
brew cask install postman 
brew cask install transmission 
brew cask install zeplin 
brew cask install calibre 
brew cask install the-unarchiver 
brew cask install visual-studio-code 
brew cask install spotify 
brew cask install fork 
brew cask install iterm2 
brew cask install google-drive-file-stream 
brew cask install spectacle 
brew cask install istat-menus 
brew cask install bartender 
brew cask install whatsapp