gui:
  showCommandLog: false

# Let Homebrew handle updates
update:
  method: never 

git:
  # Don't automatically fetch because this prompts me to unlock
  # my 1password vault all the time. I'll do it manually.
  autoFetch: false
